spring:
  application:
    name: java-e-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/cosmo_cats
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false
