spring:
  application:
    name: java-e-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/cosmo_cats
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://example.com/.well-known/jwks.json

      client:
        registration:
          github:
            client-id: Ov23lioyBbkOz3x9VFrF
            client-secret: 8ccf82c456fc7561c853fab2869858a205b21368
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

springdoc:
  api-docs:
    path: /api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false

security:
  api-key: COSMO-SECRET-KEY-123
