spring:
  application:
    name: java-e-commerce

springdoc:
  api-docs:
    path: /api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false
